{"nodes":[{"pos":[720,868],"content":"The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.","pos":[0,148]}]},{"pos":[881,1548],"content":"Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information. This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.       This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information. This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.       This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.","pos":[0,665],"nodes":[{"content":"Unlike &lt;xref:System.IO.DirectoryNotFoundException&gt;, this exception does not provide any path information.","pos":[0,105],"source":"Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information."},{"content":"This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.","pos":[106,260]},{"content":"This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: &lt;xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A&gt;,&lt;xref:System.AddIn.Hosting.AddInStore.Rebuild%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A&gt;, &lt;xref:System.AddIn.Hosting.AddInStore.Update%2A&gt;, and &lt;xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A&gt;.","pos":[267,665],"source":"       This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>."}]}]},{"pos":[2197,2309],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class."},{"pos":[3019,3158],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with the specified message."},{"pos":[3316,3343],"content":"A description of the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"A description of the error.","pos":[0,27]}]},{"pos":[4212,4377],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialization and streaming context information.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with serialization and streaming context information."},{"pos":[4389,4604],"content":"This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream.","pos":[0,120]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[121,215],"source":" For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[4887,4914],"content":"The serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The serialized object data.","pos":[0,27]}]},{"pos":[5010,5081],"content":"The contextual information about the source or destination object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination object data.","pos":[0,71]}]},{"pos":[5772,5986],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the specified message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with the specified message and a reference to the inner exception that is the cause of this exception."},{"pos":[5999,6803],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","pos":[0,797],"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed to the constructor, or a null reference if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,435],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of the &lt;xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException&gt; class.","pos":[442,592],"source":"       The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[598,797],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]}]},{"pos":[6988,7015],"content":"A description of the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"A description of the error.","pos":[0,27]}]},{"pos":[7089,7288],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.","pos":[58,199],"source":" If the `innerException` parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException\n  id: InvalidPipelineStoreException\n  children:\n  - System.AddIn.Hosting.InvalidPipelineStoreException.#ctor\n  - System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)\n  - System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: InvalidPipelineStoreException\n  nameWithType: InvalidPipelineStoreException\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException\n  type: Class\n  summary: The exception that is thrown when a directory is not found and the user does not have permission to access the pipeline root path or an add-in path.\n  remarks: \"Unlike <xref:System.IO.DirectoryNotFoundException>, this exception does not provide any path information. This prevents a malicious user from deliberately specifying erroneous paths and using the information returned by the exception to determine actual paths.  \\n  \\n This exception is thrown by the following discovery methods that build and update the store of add-in and pipeline information: <xref:System.AddIn.Hosting.AddInStore.FindAddIns%2A>,<xref:System.AddIn.Hosting.AddInStore.Rebuild%2A>, <xref:System.AddIn.Hosting.AddInStore.RebuildAddIns%2A>, <xref:System.AddIn.Hosting.AddInStore.Update%2A>, and <xref:System.AddIn.Hosting.AddInStore.UpdateAddIns%2A>.\"\n  syntax:\n    content: 'public class InvalidPipelineStoreException : Exception'\n  inheritance:\n  - System.Exception\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor\n  id: '#ctor'\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  langs:\n  - csharp\n  name: InvalidPipelineStoreException()\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException()\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException()\n  type: Constructor\n  assemblies:\n  - System.AddIn\n  namespace: System.AddIn.Hosting\n  summary: Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class.\n  syntax:\n    content: public InvalidPipelineStoreException ();\n    parameters: []\n  overload: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  langs:\n  - csharp\n  name: InvalidPipelineStoreException(String)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(String)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(String)\n  type: Constructor\n  assemblies:\n  - System.AddIn\n  namespace: System.AddIn.Hosting\n  summary: Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with the specified message.\n  syntax:\n    content: public InvalidPipelineStoreException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A description of the error.\n  overload: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  langs:\n  - csharp\n  name: InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.AddIn\n  namespace: System.AddIn.Hosting\n  summary: Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with serialization and streaming context information.\n  remarks: This constructor is called during deserialization to reconstitute an exception object that is transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).\n  syntax:\n    content: protected InvalidPipelineStoreException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination object data.\n  overload: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  langs:\n  - csharp\n  name: InvalidPipelineStoreException(String,Exception)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(String,Exception)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.AddIn\n  namespace: System.AddIn.Hosting\n  summary: Initializes a new instance of the <xref href=\"System.AddIn.Hosting.InvalidPipelineStoreException\"></xref> class with the specified message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed to the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of the <xref:System.AddIn.Hosting.AddInSegmentDirectoryNotFoundException> class.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public InvalidPipelineStoreException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: A description of the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception.\n  overload: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Exception\n  isExternal: false\n  name: System.Exception\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  isExternal: false\n  name: InvalidPipelineStoreException()\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException()\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException()\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String)\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  isExternal: false\n  name: InvalidPipelineStoreException(String)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(String)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  isExternal: false\n  name: InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor(System.String,System.Exception)\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  isExternal: false\n  name: InvalidPipelineStoreException(String,Exception)\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException(String,Exception)\n  fullName: System.AddIn.Hosting.InvalidPipelineStoreException.InvalidPipelineStoreException(String,Exception)\n- uid: System.AddIn.Hosting.InvalidPipelineStoreException.#ctor*\n  parent: System.AddIn.Hosting.InvalidPipelineStoreException\n  isExternal: false\n  name: InvalidPipelineStoreException\n  nameWithType: InvalidPipelineStoreException.InvalidPipelineStoreException\n"}