{"nodes":[{"pos":[630,705],"content":"The exception that is thrown when something has gone wrong during remoting.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when something has gone wrong during remoting.","pos":[0,75]}]},{"pos":[718,1049],"content":"RemotingException uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.       RemotingException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.       For a list of initial property values for an instance of RemotingException, see the RemotingException constructors.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"RemotingException uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.       RemotingException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.       For a list of initial property values for an instance of RemotingException, see the RemotingException constructors.","pos":[0,327],"nodes":[{"content":"RemotingException uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.","pos":[0,82]},{"content":"RemotingException uses the default &lt;xref:System.Object.Equals%2A&gt; implementation, which supports reference equality.","pos":[89,205],"source":"       RemotingException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality."},{"content":"For a list of initial property values for an instance of RemotingException, see the RemotingException constructors.","pos":[212,327]}]}]},{"pos":[1707,1834],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Remoting.RemotingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with default properties.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with default properties."},{"pos":[1847,2253],"content":"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`|   |<xref:System.Exception.Message%2A>|The empty string (\"\")|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"&lt;xref:System.Runtime.Remoting.RemotingException&gt; inherits from the &lt;xref:System.SystemException&gt; class.","pos":[0,103],"source":"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class."},{"content":"The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The empty string (\"\")|","pos":[104,399],"source":" The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`|   |<xref:System.Exception.Message%2A>|The empty string (\"\")|"}]},{"pos":[2867,2995],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Remoting.RemotingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with a specified message."},{"pos":[3008,3429],"content":"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property Type|Condition|   |-------------------|---------------|   |<xref:System.Exception.InnerException%2A>|`null`|   |<xref:System.Exception.Message%2A>|The `message` string|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"&lt;xref:System.Runtime.Remoting.RemotingException&gt; inherits from the &lt;xref:System.SystemException&gt; class.","pos":[0,103],"source":"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class."},{"content":"The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property Type|Condition|   |-------------------|---------------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>|   |&lt;xref:System.Exception.Message%2A&gt;|The <ph id=\"ph2\">`message`</ph> string|","pos":[104,416],"source":" The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property Type|Condition|   |-------------------|---------------|   |<xref:System.Exception.InnerException%2A>|`null`|   |<xref:System.Exception.Message%2A>|The `message` string|"}]},{"pos":[3576,3635],"content":"The error message that explains why the exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains why the exception occurred.","pos":[0,59]}]},{"pos":[4419,4543],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Remoting.RemotingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class from serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class from serialized data."},{"pos":[4555,4782],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. (For more information on serialization, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).)","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"(For more information on serialization, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.)","pos":[114,227],"source":" (For more information on serialization, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).)"}]},{"pos":[5053,5102],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[5198,5274],"content":"The contextual information about the source or destination of the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination of the exception.","pos":[0,76]}]},{"pos":[5452,5548],"content":"The <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">info</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"The <code>info</code> parameter is <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>."},{"pos":[6076,6285],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Remoting.RemotingException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[6298,7060],"content":"An exception that is thrown as a direct result of a previous exception will include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception will include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,180],"source":"An exception that is thrown as a direct result of a previous exception will include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[181,425],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows initial property values for an instance of the &lt;xref:System.Runtime.Remoting.RemotingException&gt; class:      |Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[432,755],"source":"       The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[7233,7292],"content":"The error message that explains why the exception occurred.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains why the exception occurred.","pos":[0,59]}]},{"pos":[7366,7666],"content":"The exception that is the cause of the current exception. If the `InnerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`InnerException`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,300],"source":" If the `InnerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Runtime.Remoting.RemotingException\n  id: RemotingException\n  children:\n  - System.Runtime.Remoting.RemotingException.#ctor\n  - System.Runtime.Remoting.RemotingException.#ctor(System.String)\n  - System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: RemotingException\n  nameWithType: RemotingException\n  fullName: System.Runtime.Remoting.RemotingException\n  type: Class\n  summary: The exception that is thrown when something has gone wrong during remoting.\n  remarks: \"RemotingException uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.  \\n  \\n RemotingException uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \\n  \\n For a list of initial property values for an instance of RemotingException, see the RemotingException constructors.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class RemotingException : SystemException\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Runtime.Remoting.RemotingException.#ctor\n  id: '#ctor'\n  parent: System.Runtime.Remoting.RemotingException\n  langs:\n  - csharp\n  name: RemotingException()\n  nameWithType: RemotingException.RemotingException()\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with default properties.\n  remarks: \"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|The empty string (\\\"\\\")|\"\n  syntax:\n    content: public RemotingException ();\n    parameters: []\n  overload: System.Runtime.Remoting.RemotingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Runtime.Remoting.RemotingException\n  langs:\n  - csharp\n  name: RemotingException(String)\n  nameWithType: RemotingException.RemotingException(String)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with a specified message.\n  remarks: \"<xref:System.Runtime.Remoting.RemotingException> inherits from the <xref:System.SystemException> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:  \\n  \\n|Property Type|Condition|  \\n|-------------------|---------------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|The `message` string|\"\n  syntax:\n    content: public RemotingException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains why the exception occurred.\n  overload: System.Runtime.Remoting.RemotingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Runtime.Remoting.RemotingException\n  langs:\n  - csharp\n  name: RemotingException(SerializationInfo,StreamingContext)\n  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class from serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. (For more information on serialization, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).)\n  syntax:\n    content: protected RemotingException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination of the exception.\n  overload: System.Runtime.Remoting.RemotingException.#ctor*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: The <code>info</code> parameter is <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>.\n  platform:\n  - net462\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Runtime.Remoting.RemotingException\n  langs:\n  - csharp\n  name: RemotingException(String,Exception)\n  nameWithType: RemotingException.RemotingException(String,Exception)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception will include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingException> class:  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public RemotingException (string message, Exception InnerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains why the exception occurred.\n    - id: InnerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `InnerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.Runtime.Remoting.RemotingException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n- uid: System.ArgumentNullException\n  isExternal: true\n  name: System.ArgumentNullException\n- uid: System.Runtime.Remoting.RemotingException.#ctor\n  parent: System.Runtime.Remoting.RemotingException\n  isExternal: false\n  name: RemotingException()\n  nameWithType: RemotingException.RemotingException()\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException()\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)\n  parent: System.Runtime.Remoting.RemotingException\n  isExternal: false\n  name: RemotingException(String)\n  nameWithType: RemotingException.RemotingException(String)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Runtime.Remoting.RemotingException\n  isExternal: false\n  name: RemotingException(SerializationInfo,StreamingContext)\n  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)\n  parent: System.Runtime.Remoting.RemotingException\n  isExternal: false\n  name: RemotingException(String,Exception)\n  nameWithType: RemotingException.RemotingException(String,Exception)\n  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Runtime.Remoting.RemotingException.#ctor*\n  parent: System.Runtime.Remoting.RemotingException\n  isExternal: false\n  name: RemotingException\n  nameWithType: RemotingException.RemotingException\n"}