{"nodes":[{"pos":[576,719],"content":"The exception that is thrown when a binding system or another schema representation system for XAML reports an exception to the schema context.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when a binding system or another schema representation system for XAML reports an exception to the schema context.","pos":[0,143]}]},{"pos":[731,1365],"content":"The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, or <xref:System.Xaml.XamlServices>). A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName>-true property for a <xref:System.Xaml.XamlObjectWriterException>, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer.","needQuote":true,"needEscape":true,"nodes":[{"content":"The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, or <xref:System.Xaml.XamlServices>). A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName>-true property for a <xref:System.Xaml.XamlObjectWriterException>, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer.","pos":[0,634],"nodes":[{"content":"The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (&lt;xref:System.Xaml.XamlXmlReader&gt;, &lt;xref:System.Xaml.XamlObjectWriter&gt;, or &lt;xref:System.Xaml.XamlServices&gt;).","pos":[0,259],"source":"The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, or <xref:System.Xaml.XamlServices>)."},{"content":"A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the &lt;xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName&gt;-true property for a &lt;xref:System.Xaml.XamlObjectWriterException&gt;, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer.","pos":[260,634],"source":" A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName>-true property for a <xref:System.Xaml.XamlObjectWriterException>, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer."}]}]},{"pos":[2199,2348],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlSchemaException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a system-supplied message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a system-supplied message that describes the error."},{"pos":[2922,3065],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlSchemaException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified message that describes the error.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a specified message that describes the error."},{"pos":[3213,3375],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[4118,4232],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlSchemaException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with serialized data."},{"pos":[4505,4554],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[4650,4709],"content":"The contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]},{"pos":[5274,5473],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Xaml.XamlSchemaException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[5485,5912],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","needQuote":true,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[6086,6248],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]},{"pos":[6322,6622],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,300],"source":" If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Xaml.XamlSchemaException\n  id: XamlSchemaException\n  children:\n  - System.Xaml.XamlSchemaException.#ctor\n  - System.Xaml.XamlSchemaException.#ctor(System.String)\n  - System.Xaml.XamlSchemaException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlSchemaException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: XamlSchemaException\n  nameWithType: XamlSchemaException\n  fullName: System.Xaml.XamlSchemaException\n  type: Class\n  summary: The exception that is thrown when a binding system or another schema representation system for XAML reports an exception to the schema context.\n  remarks: The XamlSchemaException is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, or <xref:System.Xaml.XamlServices>). A XamlSchemaException is typically passed as the inner exception for other exceptions, such as the <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=fullName>-true property for a <xref:System.Xaml.XamlObjectWriterException>, so it should be uncommon to catch a XamlSchemaException directly unless you are implementing a component such as a specialized object writer.\n  syntax:\n    content: 'public class XamlSchemaException : System.Xaml.XamlException'\n  inheritance:\n  - System.Exception\n  - System.Xaml.XamlException\n  implements: []\n  inheritedMembers:\n  - System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlException.LineNumber\n  - System.Xaml.XamlException.LinePosition\n  - System.Xaml.XamlException.Message\n  platform:\n  - net462\n- uid: System.Xaml.XamlSchemaException.#ctor\n  id: '#ctor'\n  parent: System.Xaml.XamlSchemaException\n  langs:\n  - csharp\n  name: XamlSchemaException()\n  nameWithType: XamlSchemaException.XamlSchemaException()\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException()\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a system-supplied message that describes the error.\n  syntax:\n    content: public XamlSchemaException ();\n    parameters: []\n  overload: System.Xaml.XamlSchemaException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlSchemaException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Xaml.XamlSchemaException\n  langs:\n  - csharp\n  name: XamlSchemaException(String)\n  nameWithType: XamlSchemaException.XamlSchemaException(String)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(String)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a specified message that describes the error.\n  syntax:\n    content: public XamlSchemaException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: System.Xaml.XamlSchemaException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlSchemaException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Xaml.XamlSchemaException\n  langs:\n  - csharp\n  name: XamlSchemaException(SerializationInfo,StreamingContext)\n  nameWithType: XamlSchemaException.XamlSchemaException(SerializationInfo,StreamingContext)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with serialized data.\n  syntax:\n    content: protected XamlSchemaException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Xaml.XamlSchemaException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Xaml.XamlSchemaException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Xaml.XamlSchemaException\n  langs:\n  - csharp\n  name: XamlSchemaException(String,Exception)\n  nameWithType: XamlSchemaException.XamlSchemaException(String,Exception)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlSchemaException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.\n  syntax:\n    content: public XamlSchemaException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.Xaml.XamlSchemaException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Xaml.XamlException\n  isExternal: false\n  name: System.Xaml.XamlException\n- uid: System.Xaml.XamlSchemaException.#ctor\n  parent: System.Xaml.XamlSchemaException\n  isExternal: false\n  name: XamlSchemaException()\n  nameWithType: XamlSchemaException.XamlSchemaException()\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException()\n- uid: System.Xaml.XamlSchemaException.#ctor(System.String)\n  parent: System.Xaml.XamlSchemaException\n  isExternal: false\n  name: XamlSchemaException(String)\n  nameWithType: XamlSchemaException.XamlSchemaException(String)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Xaml.XamlSchemaException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Xaml.XamlSchemaException\n  isExternal: false\n  name: XamlSchemaException(SerializationInfo,StreamingContext)\n  nameWithType: XamlSchemaException.XamlSchemaException(SerializationInfo,StreamingContext)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Xaml.XamlSchemaException.#ctor(System.String,System.Exception)\n  parent: System.Xaml.XamlSchemaException\n  isExternal: false\n  name: XamlSchemaException(String,Exception)\n  nameWithType: XamlSchemaException.XamlSchemaException(String,Exception)\n  fullName: System.Xaml.XamlSchemaException.XamlSchemaException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Xaml.XamlSchemaException.#ctor*\n  parent: System.Xaml.XamlSchemaException\n  isExternal: false\n  name: XamlSchemaException\n  nameWithType: XamlSchemaException.XamlSchemaException\n"}