{"nodes":[{"pos":[574,686],"content":"Thrown when an attempt is made to add an object to the identity cache by using a key that is already being used.","needQuote":true,"needEscape":true,"nodes":[{"content":"Thrown when an attempt is made to add an object to the identity cache by using a key that is already being used.","pos":[0,112]}]},{"pos":[1338,1438],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Linq.DuplicateKeyException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class."},{"pos":[1592,1649],"content":"The duplicate key that caused the exception to be thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The duplicate key that caused the exception to be thrown.","pos":[0,57]}]},{"pos":[2245,2409],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Linq.DuplicateKeyException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by referencing the duplicate key and providing an error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class by referencing the duplicate key and providing an error message."},{"pos":[2579,2636],"content":"The duplicate key that caused the exception to be thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The duplicate key that caused the exception to be thrown.","pos":[0,57]}]},{"pos":[2700,2751],"content":"The message to appear when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message to appear when the exception is thrown.","pos":[0,51]}]},{"pos":[3411,3642],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Data.Linq.DuplicateKeyException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class by referencing the duplicate key, providing an error message, and specifying the exception that caused this exception to be thrown.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class by referencing the duplicate key, providing an error message, and specifying the exception that caused this exception to be thrown."},{"pos":[3838,3895],"content":"The duplicate key that caused the exception to be thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The duplicate key that caused the exception to be thrown.","pos":[0,57]}]},{"pos":[3959,4010],"content":"The message to appear when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message to appear when the exception is thrown.","pos":[0,51]}]},{"pos":[4084,4206],"content":"The previous exception that caused the <bpt id=\"p1\">&lt;xref href=\"System.Data.Linq.DuplicateKeyException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> exception to be thrown.","needQuote":true,"needEscape":true,"source":"The previous exception that caused the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> exception to be thrown."},{"pos":[4651,4693],"content":"Gets the object that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the object that caused the exception.","pos":[0,42]}]},{"pos":[4804,4841],"content":"The object that caused the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that caused the exception.","pos":[0,37]}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Data.Linq.DuplicateKeyException\n  id: DuplicateKeyException\n  children:\n  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object)\n  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)\n  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)\n  - System.Data.Linq.DuplicateKeyException.Object\n  langs:\n  - csharp\n  name: DuplicateKeyException\n  nameWithType: DuplicateKeyException\n  fullName: System.Data.Linq.DuplicateKeyException\n  type: Class\n  summary: Thrown when an attempt is made to add an object to the identity cache by using a key that is already being used.\n  syntax:\n    content: 'public class DuplicateKeyException : InvalidOperationException'\n  inheritance:\n  - System.InvalidOperationException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)\n  id: '#ctor(System.Object)'\n  parent: System.Data.Linq.DuplicateKeyException\n  langs:\n  - csharp\n  name: DuplicateKeyException(Object)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)\n  type: Constructor\n  assemblies:\n  - System.Data.Linq\n  namespace: System.Data.Linq\n  summary: Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class.\n  syntax:\n    content: public DuplicateKeyException (object duplicate);\n    parameters:\n    - id: duplicate\n      type: System.Object\n      description: The duplicate key that caused the exception to be thrown.\n  overload: System.Data.Linq.DuplicateKeyException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)\n  id: '#ctor(System.Object,System.String)'\n  parent: System.Data.Linq.DuplicateKeyException\n  langs:\n  - csharp\n  name: DuplicateKeyException(Object,String)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)\n  type: Constructor\n  assemblies:\n  - System.Data.Linq\n  namespace: System.Data.Linq\n  summary: Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class by referencing the duplicate key and providing an error message.\n  syntax:\n    content: public DuplicateKeyException (object duplicate, string message);\n    parameters:\n    - id: duplicate\n      type: System.Object\n      description: The duplicate key that caused the exception to be thrown.\n    - id: message\n      type: System.String\n      description: The message to appear when the exception is thrown.\n  overload: System.Data.Linq.DuplicateKeyException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)\n  id: '#ctor(System.Object,System.String,System.Exception)'\n  parent: System.Data.Linq.DuplicateKeyException\n  langs:\n  - csharp\n  name: DuplicateKeyException(Object,String,Exception)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Data.Linq\n  namespace: System.Data.Linq\n  summary: Initializes a new instance of the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> class by referencing the duplicate key, providing an error message, and specifying the exception that caused this exception to be thrown.\n  syntax:\n    content: public DuplicateKeyException (object duplicate, string message, Exception innerException);\n    parameters:\n    - id: duplicate\n      type: System.Object\n      description: The duplicate key that caused the exception to be thrown.\n    - id: message\n      type: System.String\n      description: The message to appear when the exception is thrown.\n    - id: innerException\n      type: System.Exception\n      description: The previous exception that caused the <xref href=\"System.Data.Linq.DuplicateKeyException\"></xref> exception to be thrown.\n  overload: System.Data.Linq.DuplicateKeyException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.Linq.DuplicateKeyException.Object\n  id: Object\n  parent: System.Data.Linq.DuplicateKeyException\n  langs:\n  - csharp\n  name: Object\n  nameWithType: DuplicateKeyException.Object\n  fullName: System.Data.Linq.DuplicateKeyException.Object\n  type: Property\n  assemblies:\n  - System.Data.Linq\n  namespace: System.Data.Linq\n  summary: Gets the object that caused the exception.\n  syntax:\n    content: public object Object { get; }\n    return:\n      type: System.Object\n      description: The object that caused the exception.\n  overload: System.Data.Linq.DuplicateKeyException.Object*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.InvalidOperationException\n  isExternal: false\n  name: System.InvalidOperationException\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: DuplicateKeyException(Object)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)\n- uid: System.Object\n  parent: System\n  isExternal: true\n  name: Object\n  nameWithType: Object\n  fullName: System.Object\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: DuplicateKeyException(Object,String)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: DuplicateKeyException(Object,String,Exception)\n  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)\n  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Data.Linq.DuplicateKeyException.Object\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: Object\n  nameWithType: DuplicateKeyException.Object\n  fullName: System.Data.Linq.DuplicateKeyException.Object\n- uid: System.Data.Linq.DuplicateKeyException.#ctor*\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: DuplicateKeyException\n  nameWithType: DuplicateKeyException.DuplicateKeyException\n- uid: System.Data.Linq.DuplicateKeyException.Object*\n  parent: System.Data.Linq.DuplicateKeyException\n  isExternal: false\n  name: Object\n  nameWithType: DuplicateKeyException.Object\n"}