{"nodes":[{"pos":[669,796],"content":"The exception that is thrown when a <bpt id=\"p1\">&lt;xref href=\"System.Threading.Thread\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> is interrupted while it is in a waiting state.","needQuote":true,"needEscape":true,"source":"The exception that is thrown when a <xref href=\"System.Threading.Thread\"></xref> is interrupted while it is in a waiting state."},{"pos":[809,1614],"content":"After a thread is created, it is in one or more <xref:System.Threading.ThreadState> states until it is destroyed. Calling <xref:System.Threading.Thread.Interrupt%2A> when a thread is in the <xref:System.Threading.ThreadState> state will cause a ThreadInterruptedException to be thrown in the target thread. If the thread is not in the <xref:System.Threading.ThreadState> state, the exception is not thrown until the thread enters that state. If the thread never blocks, it could complete without ever being interrupted.       ThreadInterruptedException uses the HRESULT COR_E_THREADINTERRUPTED, which has the value 0x80131519.       For a list of initial property values for an instance of ThreadInterruptedException, see the <xref:System.Threading.ThreadInterruptedException.%23ctor%2A> constructors.","needQuote":false,"needEscape":true,"nodes":[{"content":"After a thread is created, it is in one or more <xref:System.Threading.ThreadState> states until it is destroyed. Calling <xref:System.Threading.Thread.Interrupt%2A> when a thread is in the <xref:System.Threading.ThreadState> state will cause a ThreadInterruptedException to be thrown in the target thread. If the thread is not in the <xref:System.Threading.ThreadState> state, the exception is not thrown until the thread enters that state. If the thread never blocks, it could complete without ever being interrupted.       ThreadInterruptedException uses the HRESULT COR_E_THREADINTERRUPTED, which has the value 0x80131519.       For a list of initial property values for an instance of ThreadInterruptedException, see the <xref:System.Threading.ThreadInterruptedException.%23ctor%2A> constructors.","pos":[0,801],"nodes":[{"content":"After a thread is created, it is in one or more &lt;xref:System.Threading.ThreadState&gt; states until it is destroyed.","pos":[0,113],"source":"After a thread is created, it is in one or more <xref:System.Threading.ThreadState> states until it is destroyed."},{"content":"Calling &lt;xref:System.Threading.Thread.Interrupt%2A&gt; when a thread is in the &lt;xref:System.Threading.ThreadState&gt; state will cause a ThreadInterruptedException to be thrown in the target thread.","pos":[114,306],"source":" Calling <xref:System.Threading.Thread.Interrupt%2A> when a thread is in the <xref:System.Threading.ThreadState> state will cause a ThreadInterruptedException to be thrown in the target thread."},{"content":"If the thread is not in the &lt;xref:System.Threading.ThreadState&gt; state, the exception is not thrown until the thread enters that state.","pos":[307,441],"source":" If the thread is not in the <xref:System.Threading.ThreadState> state, the exception is not thrown until the thread enters that state."},{"content":"If the thread never blocks, it could complete without ever being interrupted.","pos":[442,519]},{"content":"ThreadInterruptedException uses the HRESULT COR_E_THREADINTERRUPTED, which has the value 0x80131519.","pos":[526,626]},{"content":"For a list of initial property values for an instance of ThreadInterruptedException, see the &lt;xref:System.Threading.ThreadInterruptedException.%23ctor%2A&gt; constructors.","pos":[633,801],"source":"       For a list of initial property values for an instance of ThreadInterruptedException, see the <xref:System.Threading.ThreadInterruptedException.%23ctor%2A> constructors."}]}]},{"pos":[2787,2916],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Threading.ThreadInterruptedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with default properties.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with default properties."},{"pos":[2929,3240],"content":"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.","pos":[0,124],"source":"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[130,306],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]},{"pos":[3900,4036],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Threading.ThreadInterruptedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with a specified error message."},{"pos":[4049,4350],"content":"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.","pos":[0,124],"source":"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[130,296],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[4506,4567],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[5388,5514],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Threading.ThreadInterruptedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with serialized data."},{"pos":[5526,5734],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).","needQuote":true,"needEscape":true,"nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[114,208],"source":" For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[6014,6157],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[6253,6379],"content":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that contains contextual information about the source or destination.","pos":[0,126],"source":"The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."}]},{"pos":[7022,7233],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Threading.ThreadInterruptedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[7246,8006],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.Threading.ThreadInterruptedException&gt;.","pos":[434,558],"source":"       The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[564,753],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[8188,8249],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[8323,8623],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,300],"source":" If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Threading.ThreadInterruptedException\n  id: ThreadInterruptedException\n  children:\n  - System.Threading.ThreadInterruptedException.#ctor\n  - System.Threading.ThreadInterruptedException.#ctor(System.String)\n  - System.Threading.ThreadInterruptedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Threading.ThreadInterruptedException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ThreadInterruptedException\n  nameWithType: ThreadInterruptedException\n  fullName: System.Threading.ThreadInterruptedException\n  type: Class\n  summary: The exception that is thrown when a <xref href=\"System.Threading.Thread\"></xref> is interrupted while it is in a waiting state.\n  remarks: \"After a thread is created, it is in one or more <xref:System.Threading.ThreadState> states until it is destroyed. Calling <xref:System.Threading.Thread.Interrupt%2A> when a thread is in the <xref:System.Threading.ThreadState> state will cause a ThreadInterruptedException to be thrown in the target thread. If the thread is not in the <xref:System.Threading.ThreadState> state, the exception is not thrown until the thread enters that state. If the thread never blocks, it could complete without ever being interrupted.  \\n  \\n ThreadInterruptedException uses the HRESULT COR_E_THREADINTERRUPTED, which has the value 0x80131519.  \\n  \\n For a list of initial property values for an instance of ThreadInterruptedException, see the <xref:System.Threading.ThreadInterruptedException.%23ctor%2A> constructors.\"\n  example:\n  - \"The following code example shows the behavior of a running thread when it is interrupted and subsequently gets blocked.  \\n  \\n [!code-cpp[System.Threading.Thread.Interrupt#1](~/add/codesnippet/cpp/t-system.threading.threa_1_1.cpp)]\\n [!code-vb[System.Threading.Thread.Interrupt#1](~/add/codesnippet/visualbasic/t-system.threading.threa_1_1.vb)]\\n [!code-cs[System.Threading.Thread.Interrupt#1](~/add/codesnippet/csharp/t-system.threading.threa_1_1.cs)]\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class ThreadInterruptedException : SystemException\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Threading.ThreadInterruptedException.#ctor\n  id: '#ctor'\n  parent: System.Threading.ThreadInterruptedException\n  langs:\n  - csharp\n  name: ThreadInterruptedException()\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException()\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Threading\n  summary: Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with default properties.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public ThreadInterruptedException ();\n    parameters: []\n  overload: System.Threading.ThreadInterruptedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Threading.ThreadInterruptedException\n  langs:\n  - csharp\n  name: ThreadInterruptedException(String)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(String)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Threading\n  summary: Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ThreadInterruptedException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.Threading.ThreadInterruptedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Threading.ThreadInterruptedException\n  langs:\n  - csharp\n  name: ThreadInterruptedException(SerializationInfo,StreamingContext)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(SerializationInfo,StreamingContext)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Threading\n  summary: Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).\n  syntax:\n    content: protected ThreadInterruptedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination.\n  overload: System.Threading.ThreadInterruptedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Threading.ThreadInterruptedException\n  langs:\n  - csharp\n  name: ThreadInterruptedException(String,Exception)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(String,Exception)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(String,Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Threading\n  summary: Initializes a new instance of the <xref href=\"System.Threading.ThreadInterruptedException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Threading.ThreadInterruptedException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ThreadInterruptedException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.Threading.ThreadInterruptedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n- uid: System.Threading.ThreadInterruptedException.#ctor\n  parent: System.Threading.ThreadInterruptedException\n  isExternal: false\n  name: ThreadInterruptedException()\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException()\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException()\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.String)\n  parent: System.Threading.ThreadInterruptedException\n  isExternal: false\n  name: ThreadInterruptedException(String)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(String)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Threading.ThreadInterruptedException\n  isExternal: false\n  name: ThreadInterruptedException(SerializationInfo,StreamingContext)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(SerializationInfo,StreamingContext)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Threading.ThreadInterruptedException.#ctor(System.String,System.Exception)\n  parent: System.Threading.ThreadInterruptedException\n  isExternal: false\n  name: ThreadInterruptedException(String,Exception)\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException(String,Exception)\n  fullName: System.Threading.ThreadInterruptedException.ThreadInterruptedException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Threading.ThreadInterruptedException.#ctor*\n  parent: System.Threading.ThreadInterruptedException\n  isExternal: false\n  name: ThreadInterruptedException\n  nameWithType: ThreadInterruptedException.ThreadInterruptedException\n"}