{"nodes":[{"pos":[480,596],"content":"Provides data for the event that is raised when there is an exception that is not handled in any application domain.","needQuote":true,"needEscape":true,"nodes":[{"content":"Provides data for the event that is raised when there is an exception that is not handled in any application domain.","pos":[0,116]}]},{"pos":[609,1060],"content":"UnhandledExceptionEventArgs provides access to the exception object and a flag indicating whether the common language runtime is terminating. The UnhandledExceptionEventArgs is one of the parameters passed into <xref:System.UnhandledExceptionEventHandler> for the <xref:System.AppDomain.UnhandledException?displayProperty=fullName> event.       For more information about event handler delegates, see [Events](~/add/includes/ajax-current-ext-md.md).","needQuote":false,"needEscape":true,"nodes":[{"content":"UnhandledExceptionEventArgs provides access to the exception object and a flag indicating whether the common language runtime is terminating.","pos":[0,141]},{"content":"The UnhandledExceptionEventArgs is one of the parameters passed into &lt;xref:System.UnhandledExceptionEventHandler&gt; for the &lt;xref:System.AppDomain.UnhandledException?displayProperty=fullName&gt; event.","pos":[142,338],"source":" The UnhandledExceptionEventArgs is one of the parameters passed into <xref:System.UnhandledExceptionEventHandler> for the <xref:System.AppDomain.UnhandledException?displayProperty=fullName> event."},{"content":"For more information about event handler delegates, see <bpt id=\"p1\">[</bpt>Events<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[345,449],"source":"       For more information about event handler delegates, see [Events](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[1799,1968],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.UnhandledExceptionEventArgs\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with the exception object and a common language runtime termination flag.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.UnhandledExceptionEventArgs\"></xref> class with the exception object and a common language runtime termination flag."},{"pos":[2148,2182],"content":"The exception that is not handled.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is not handled.","pos":[0,34]}]},{"pos":[2253,2419],"content":"<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> if the runtime is terminating; otherwise, <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"<xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"></xref> if the runtime is terminating; otherwise, <xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"></xref>."},{"pos":[2881,2917],"content":"Gets the unhandled exception object.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the unhandled exception object.","pos":[0,36]}]},{"pos":[2930,4263],"content":"This property returns an object of type <xref:System.Object> rather than one derived from <xref:System.Exception>. Although the Common Language Specification requires that all exception types derive from <xref:System.Exception>, it is possible for methods to throw exceptions with objects not derived from <xref:System.Exception>. You can do the following to work with this exception:      -   Apply the  <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute> attribute with a <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute.WrapNonExceptionThrows%2A?displayProperty=fullName> value of `true` to the assembly that contains the event handler. This wraps all exceptions not derived from the <xref:System.Exception> class in a <xref:System.Runtime.CompilerServices.RuntimeWrappedException> object. You can then safely cast (in C#) or convert (in Visual Basic) the object returned by this property to an <xref:System.Exception> object, and retrieve the original exception object from the <xref:System.Runtime.CompilerServices.RuntimeWrappedException.WrappedException%2A?displayProperty=fullName> property. Note that some compilers, such as the C# and Visual Basic compilers, automatically apply this attribute.      -   Cast the object returned by this property to an <xref:System.Exception> object.","needQuote":false,"needEscape":true,"nodes":[{"content":"This property returns an object of type &lt;xref:System.Object&gt; rather than one derived from &lt;xref:System.Exception&gt;.","pos":[0,114],"source":"This property returns an object of type <xref:System.Object> rather than one derived from <xref:System.Exception>."},{"content":"Although the Common Language Specification requires that all exception types derive from &lt;xref:System.Exception&gt;, it is possible for methods to throw exceptions with objects not derived from &lt;xref:System.Exception&gt;.","pos":[115,330],"source":" Although the Common Language Specification requires that all exception types derive from <xref:System.Exception>, it is possible for methods to throw exceptions with objects not derived from <xref:System.Exception>."},{"content":"You can do the following to work with this exception:      -   Apply the  &lt;xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute&gt; attribute with a &lt;xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute.WrapNonExceptionThrows%2A?displayProperty=fullName&gt; value of <ph id=\"ph1\">`true`</ph> to the assembly that contains the event handler.","pos":[331,675],"source":" You can do the following to work with this exception:      -   Apply the  <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute> attribute with a <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute.WrapNonExceptionThrows%2A?displayProperty=fullName> value of `true` to the assembly that contains the event handler."},{"content":"This wraps all exceptions not derived from the &lt;xref:System.Exception&gt; class in a &lt;xref:System.Runtime.CompilerServices.RuntimeWrappedException&gt; object.","pos":[676,828],"source":" This wraps all exceptions not derived from the <xref:System.Exception> class in a <xref:System.Runtime.CompilerServices.RuntimeWrappedException> object."},{"content":"You can then safely cast (in C#) or convert (in Visual Basic) the object returned by this property to an &lt;xref:System.Exception&gt; object, and retrieve the original exception object from the &lt;xref:System.Runtime.CompilerServices.RuntimeWrappedException.WrappedException%2A?displayProperty=fullName&gt; property.","pos":[829,1135],"source":" You can then safely cast (in C#) or convert (in Visual Basic) the object returned by this property to an <xref:System.Exception> object, and retrieve the original exception object from the <xref:System.Runtime.CompilerServices.RuntimeWrappedException.WrappedException%2A?displayProperty=fullName> property."},{"content":"Note that some compilers, such as the C# and Visual Basic compilers, automatically apply this attribute.","pos":[1136,1240]},{"content":"-   Cast the object returned by this property to an &lt;xref:System.Exception&gt; object.","pos":[1246,1329],"source":"      -   Cast the object returned by this property to an <xref:System.Exception> object."}]},{"pos":[5110,5141],"content":"The unhandled exception object.","needQuote":true,"needEscape":true,"nodes":[{"content":"The unhandled exception object.","pos":[0,31]}]},{"pos":[5603,5664],"content":"Indicates whether the common language runtime is terminating.","needQuote":true,"needEscape":true,"nodes":[{"content":"Indicates whether the common language runtime is terminating.","pos":[0,61]}]},{"pos":[5677,6760],"content":"Beginning with the .NET Framework version 2.0, this property returns `true` for most unhandled exceptions, unless an application compatibility flag is used to revert to the behavior of versions 1.0 and 1.1. The reason is that most unhandled exceptions in threads, including thread pool threads, are allowed to proceed naturally, which normally results in termination of the application. For more information, including a list of cases in which the runtime does not terminate, see [Exceptions in Managed Threads](~/add/includes/ajax-current-ext-md.md).      ## Version Information    The following applies to the .NET Framework versions 1.0 and 1.1: This property returns `true` when an exception is received in, but not handled by, an application's main thread. This property also returns `true` if an unmanaged thread is executing managed code and receives an unhandled exception. Finally, this property returns `false` for thread pool threads and managed threads created by an application, because versions 1.0 and 1.1 catch unhandled exceptions in such threads and ignore them.","needQuote":false,"needEscape":true,"nodes":[{"content":"Beginning with the .NET Framework version 2.0, this property returns <ph id=\"ph1\">`true`</ph> for most unhandled exceptions, unless an application compatibility flag is used to revert to the behavior of versions 1.0 and 1.1.","pos":[0,206],"source":"Beginning with the .NET Framework version 2.0, this property returns `true` for most unhandled exceptions, unless an application compatibility flag is used to revert to the behavior of versions 1.0 and 1.1."},{"content":"The reason is that most unhandled exceptions in threads, including thread pool threads, are allowed to proceed naturally, which normally results in termination of the application.","pos":[207,386]},{"content":"For more information, including a list of cases in which the runtime does not terminate, see <bpt id=\"p1\">[</bpt>Exceptions in Managed Threads<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[387,551],"source":" For more information, including a list of cases in which the runtime does not terminate, see [Exceptions in Managed Threads](~/add/includes/ajax-current-ext-md.md)."},{"content":"Version Information    The following applies to the .NET Framework versions 1.0 and 1.1: This property returns <ph id=\"ph1\">`true`</ph> when an exception is received in, but not handled by, an application's main thread.","pos":[560,761],"source":"      ## Version Information    The following applies to the .NET Framework versions 1.0 and 1.1: This property returns `true` when an exception is received in, but not handled by, an application's main thread."},{"content":"This property also returns <ph id=\"ph1\">`true`</ph> if an unmanaged thread is executing managed code and receives an unhandled exception.","pos":[762,881],"source":" This property also returns `true` if an unmanaged thread is executing managed code and receives an unhandled exception."},{"content":"Finally, this property returns <ph id=\"ph1\">`false`</ph> for thread pool threads and managed threads created by an application, because versions 1.0 and 1.1 catch unhandled exceptions in such threads and ignore them.","pos":[882,1080],"source":" Finally, this property returns `false` for thread pool threads and managed threads created by an application, because versions 1.0 and 1.1 catch unhandled exceptions in such threads and ignore them."}]},{"pos":[6878,7044],"content":"<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> if the runtime is terminating; otherwise, <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"<xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"></xref> if the runtime is terminating; otherwise, <xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"></xref>."}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.UnhandledExceptionEventArgs\n  id: UnhandledExceptionEventArgs\n  children:\n  - System.UnhandledExceptionEventArgs.#ctor(System.Object,System.Boolean)\n  - System.UnhandledExceptionEventArgs.ExceptionObject\n  - System.UnhandledExceptionEventArgs.IsTerminating\n  langs:\n  - csharp\n  name: UnhandledExceptionEventArgs\n  nameWithType: UnhandledExceptionEventArgs\n  fullName: System.UnhandledExceptionEventArgs\n  type: Class\n  summary: Provides data for the event that is raised when there is an exception that is not handled in any application domain.\n  remarks: \"UnhandledExceptionEventArgs provides access to the exception object and a flag indicating whether the common language runtime is terminating. The UnhandledExceptionEventArgs is one of the parameters passed into <xref:System.UnhandledExceptionEventHandler> for the <xref:System.AppDomain.UnhandledException?displayProperty=fullName> event.  \\n  \\n For more information about event handler delegates, see [Events](~/add/includes/ajax-current-ext-md.md).\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class UnhandledExceptionEventArgs : EventArgs\n  inheritance:\n  - System.EventArgs\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.UnhandledExceptionEventArgs.#ctor(System.Object,System.Boolean)\n  id: '#ctor(System.Object,System.Boolean)'\n  parent: System.UnhandledExceptionEventArgs\n  langs:\n  - csharp\n  name: UnhandledExceptionEventArgs(Object,Boolean)\n  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Object,Boolean)\n  fullName: System.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Object,Boolean)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.UnhandledExceptionEventArgs\"></xref> class with the exception object and a common language runtime termination flag.\n  syntax:\n    content: public UnhandledExceptionEventArgs (object exception, bool isTerminating);\n    parameters:\n    - id: exception\n      type: System.Object\n      description: The exception that is not handled.\n    - id: isTerminating\n      type: System.Boolean\n      description: <xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"></xref> if the runtime is terminating; otherwise, <xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"></xref>.\n  overload: System.UnhandledExceptionEventArgs.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.UnhandledExceptionEventArgs.ExceptionObject\n  id: ExceptionObject\n  parent: System.UnhandledExceptionEventArgs\n  langs:\n  - csharp\n  name: ExceptionObject\n  nameWithType: UnhandledExceptionEventArgs.ExceptionObject\n  fullName: System.UnhandledExceptionEventArgs.ExceptionObject\n  type: Property\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Gets the unhandled exception object.\n  remarks: \"This property returns an object of type <xref:System.Object> rather than one derived from <xref:System.Exception>. Although the Common Language Specification requires that all exception types derive from <xref:System.Exception>, it is possible for methods to throw exceptions with objects not derived from <xref:System.Exception>. You can do the following to work with this exception:  \\n  \\n-   Apply the  <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute> attribute with a <xref:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute.WrapNonExceptionThrows%2A?displayProperty=fullName> value of `true` to the assembly that contains the event handler. This wraps all exceptions not derived from the <xref:System.Exception> class in a <xref:System.Runtime.CompilerServices.RuntimeWrappedException> object. You can then safely cast (in C#) or convert (in Visual Basic) the object returned by this property to an <xref:System.Exception> object, and retrieve the original exception object from the <xref:System.Runtime.CompilerServices.RuntimeWrappedException.WrappedException%2A?displayProperty=fullName> property. Note that some compilers, such as the C# and Visual Basic compilers, automatically apply this attribute.  \\n  \\n-   Cast the object returned by this property to an <xref:System.Exception> object.\"\n  example:\n  - \"The following example demonstrates the <xref:System.AppDomain.UnhandledException> event. It defines an event handler, `MyHandler`, that is invoked whenever an unhandled exception is thrown in the default application domain. It then throws two exceptions. The first is handled by a **try/catch** block. The second is unhandled and invokes the `MyHandle` routine before the application terminates.  \\n  \\n [!code-cs[AppDomain_UnhandledException#1](~/add/codesnippet/csharp/p-system.unhandledexcept_1.cs)]\\n [!code-vb[AppDomain_UnhandledException#1](~/add/codesnippet/visualbasic/p-system.unhandledexcept_1.vb)]\\n [!code-cpp[AppDomain_UnhandledException#1](~/add/codesnippet/cpp/p-system.unhandledexcept_1.cpp)]\"\n  syntax:\n    content: public object ExceptionObject { get; }\n    return:\n      type: System.Object\n      description: The unhandled exception object.\n  overload: System.UnhandledExceptionEventArgs.ExceptionObject*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.UnhandledExceptionEventArgs.IsTerminating\n  id: IsTerminating\n  parent: System.UnhandledExceptionEventArgs\n  langs:\n  - csharp\n  name: IsTerminating\n  nameWithType: UnhandledExceptionEventArgs.IsTerminating\n  fullName: System.UnhandledExceptionEventArgs.IsTerminating\n  type: Property\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Indicates whether the common language runtime is terminating.\n  remarks: \"Beginning with the .NET Framework version 2.0, this property returns `true` for most unhandled exceptions, unless an application compatibility flag is used to revert to the behavior of versions 1.0 and 1.1. The reason is that most unhandled exceptions in threads, including thread pool threads, are allowed to proceed naturally, which normally results in termination of the application. For more information, including a list of cases in which the runtime does not terminate, see [Exceptions in Managed Threads](~/add/includes/ajax-current-ext-md.md).  \\n  \\n## Version Information  \\n The following applies to the .NET Framework versions 1.0 and 1.1: This property returns `true` when an exception is received in, but not handled by, an application's main thread. This property also returns `true` if an unmanaged thread is executing managed code and receives an unhandled exception. Finally, this property returns `false` for thread pool threads and managed threads created by an application, because versions 1.0 and 1.1 catch unhandled exceptions in such threads and ignore them.\"\n  syntax:\n    content: public bool IsTerminating { get; }\n    return:\n      type: System.Boolean\n      description: <xref uid=\"langword_csharp_true\" name=\"true\" href=\"\"></xref> if the runtime is terminating; otherwise, <xref uid=\"langword_csharp_false\" name=\"false\" href=\"\"></xref>.\n  overload: System.UnhandledExceptionEventArgs.IsTerminating*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.EventArgs\n  isExternal: false\n  name: System.EventArgs\n- uid: System.UnhandledExceptionEventArgs.#ctor(System.Object,System.Boolean)\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: UnhandledExceptionEventArgs(Object,Boolean)\n  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Object,Boolean)\n  fullName: System.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Object,Boolean)\n- uid: System.Object\n  parent: System\n  isExternal: true\n  name: Object\n  nameWithType: Object\n  fullName: System.Object\n- uid: System.Boolean\n  parent: System\n  isExternal: true\n  name: Boolean\n  nameWithType: Boolean\n  fullName: System.Boolean\n- uid: System.UnhandledExceptionEventArgs.ExceptionObject\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: ExceptionObject\n  nameWithType: UnhandledExceptionEventArgs.ExceptionObject\n  fullName: System.UnhandledExceptionEventArgs.ExceptionObject\n- uid: System.UnhandledExceptionEventArgs.IsTerminating\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: IsTerminating\n  nameWithType: UnhandledExceptionEventArgs.IsTerminating\n  fullName: System.UnhandledExceptionEventArgs.IsTerminating\n- uid: System.UnhandledExceptionEventArgs.#ctor*\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: UnhandledExceptionEventArgs\n  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs\n- uid: System.UnhandledExceptionEventArgs.ExceptionObject*\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: ExceptionObject\n  nameWithType: UnhandledExceptionEventArgs.ExceptionObject\n- uid: System.UnhandledExceptionEventArgs.IsTerminating*\n  parent: System.UnhandledExceptionEventArgs\n  isExternal: false\n  name: IsTerminating\n  nameWithType: UnhandledExceptionEventArgs.IsTerminating\n"}