{"nodes":[{"pos":[472,531],"content":"The exception that is thrown when an object is not present.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when an object is not present.","pos":[0,59]}]},{"pos":[543,637],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","needQuote":true,"needEscape":true,"nodes":[{"content":"For more information about how to handle exceptions in your code, see &lt;xref:System.Exception&gt;.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]},{"pos":[1287,1374],"content":"Initializes a new instance of <bpt id=\"p1\">&lt;xref href=\"System.Data.ObjectNotFoundException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref>."},{"pos":[1386,1480],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","needQuote":true,"needEscape":true,"nodes":[{"content":"For more information about how to handle exceptions in your code, see &lt;xref:System.Exception&gt;.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]},{"pos":[2097,2217],"content":"Initializes a new instance of <bpt id=\"p1\">&lt;xref href=\"System.Data.ObjectNotFoundException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> with a specialized error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref> with a specialized error message."},{"pos":[2229,2323],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","needQuote":true,"needEscape":true,"nodes":[{"content":"For more information about how to handle exceptions in your code, see &lt;xref:System.Exception&gt;.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]},{"pos":[2475,2512],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[3116,3284],"content":"Initializes a new instance of <bpt id=\"p1\">&lt;xref href=\"System.Data.ObjectNotFoundException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class that uses a specified error message and a reference to the inner exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref> class that uses a specified error message and a reference to the inner exception."},{"pos":[3296,3390],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","needQuote":true,"needEscape":true,"nodes":[{"content":"For more information about how to handle exceptions in your code, see &lt;xref:System.Exception&gt;.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]},{"pos":[3568,3605],"content":"The message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The message that describes the error.","pos":[0,37]}]},{"pos":[3679,3877],"content":"The exception that is the cause of the current exception, or a null reference (<bpt id=\"p1\">&lt;xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> in Visual Basic) if no inner exception is specified.","needQuote":true,"needEscape":true,"source":"The exception that is the cause of the current exception, or a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic) if no inner exception is specified."}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Data.ObjectNotFoundException\n  id: ObjectNotFoundException\n  children:\n  - System.Data.ObjectNotFoundException.#ctor\n  - System.Data.ObjectNotFoundException.#ctor(System.String)\n  - System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ObjectNotFoundException\n  nameWithType: ObjectNotFoundException\n  fullName: System.Data.ObjectNotFoundException\n  type: Class\n  summary: The exception that is thrown when an object is not present.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: 'public sealed class ObjectNotFoundException : System.Data.DataException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  - System.Data.DataException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.Data.ObjectNotFoundException.#ctor\n  id: '#ctor'\n  parent: System.Data.ObjectNotFoundException\n  langs:\n  - csharp\n  name: ObjectNotFoundException()\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException()\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException()\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref>.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public ObjectNotFoundException ();\n    parameters: []\n  overload: System.Data.ObjectNotFoundException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.ObjectNotFoundException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Data.ObjectNotFoundException\n  langs:\n  - csharp\n  name: ObjectNotFoundException(String)\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String)\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String)\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref> with a specialized error message.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public ObjectNotFoundException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Data.ObjectNotFoundException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Data.ObjectNotFoundException\n  langs:\n  - csharp\n  name: ObjectNotFoundException(String,Exception)\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String,Exception)\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.ObjectNotFoundException\"></xref> class that uses a specified error message and a reference to the inner exception.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public ObjectNotFoundException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception, or a null reference (<xref uid=\"langword_csharp_Nothing\" name=\"Nothing\" href=\"\"></xref> in Visual Basic) if no inner exception is specified.\n  overload: System.Data.ObjectNotFoundException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Data.DataException\n  isExternal: false\n  name: System.Data.DataException\n- uid: System.Data.ObjectNotFoundException.#ctor\n  parent: System.Data.ObjectNotFoundException\n  isExternal: false\n  name: ObjectNotFoundException()\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException()\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException()\n- uid: System.Data.ObjectNotFoundException.#ctor(System.String)\n  parent: System.Data.ObjectNotFoundException\n  isExternal: false\n  name: ObjectNotFoundException(String)\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String)\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)\n  parent: System.Data.ObjectNotFoundException\n  isExternal: false\n  name: ObjectNotFoundException(String,Exception)\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String,Exception)\n  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Data.ObjectNotFoundException.#ctor*\n  parent: System.Data.ObjectNotFoundException\n  isExternal: false\n  name: ObjectNotFoundException\n  nameWithType: ObjectNotFoundException.ObjectNotFoundException\n"}