{"nodes":[{"pos":[555,615],"content":"Serves as the base class for application-defined exceptions.","needQuote":true,"needEscape":true,"nodes":[{"content":"Serves as the base class for application-defined exceptions.","pos":[0,60]}]},{"pos":[1538,1627],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ApplicationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class."},{"pos":[1640,2240],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"An application error has occurred.\" This message takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.ApplicationException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error, such as \"An application error has occurred.\"","pos":[0,196],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"An application error has occurred.\""},{"content":"This message takes into account the current system culture.","pos":[197,256]},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ApplicationException&gt;.","pos":[263,371],"source":"       The following table shows the initial property values for an instance of <xref:System.ApplicationException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[377,591],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]},{"pos":[2796,2916],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ApplicationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with a specified error message."},{"pos":[2929,3503],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       This message takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.ApplicationException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |`Message`|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]},{"content":"This message takes into account the current system culture.","pos":[206,265]},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ApplicationException&gt;.","pos":[272,380],"source":"       The following table shows the initial property values for an instance of <xref:System.ApplicationException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).|   |<ph id=\"ph2\">`Message`</ph>|The error message string.|","pos":[386,565],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |`Message`|The error message string.|"}]},{"pos":[3653,3688],"content":"A message that describes the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"A message that describes the error.","pos":[0,35]}]},{"pos":[4411,4521],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ApplicationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with serialized data."},{"pos":[4533,4741],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).","needQuote":true,"needEscape":true,"nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[114,208],"source":" For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[5015,5064],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[5160,5219],"content":"The contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]},{"pos":[5764,5959],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.ApplicationException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[5972,6934],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.ApplicationException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[206,388],"source":"       An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or a null reference if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[389,643],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.ApplicationException&gt;.","pos":[650,758],"source":"       The following table shows the initial property values for an instance of <xref:System.ApplicationException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[764,953],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[7110,7171],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[7245,7501],"content":"The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`innerException`</ph> parameter is not a null reference, the current exception is raised in a <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,256],"source":" If the `innerException` parameter is not a null reference, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.ApplicationException\n  id: ApplicationException\n  children:\n  - System.ApplicationException.#ctor\n  - System.ApplicationException.#ctor(System.String)\n  - System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.ApplicationException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ApplicationException\n  nameWithType: ApplicationException\n  fullName: System.ApplicationException\n  type: Class\n  summary: Serves as the base class for application-defined exceptions.\n  remarks: >-\n    > [!IMPORTANT]\n\n    >  You should derive custom exceptions from the <xref:System.Exception> class rather than the ApplicationException class.  You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class ApplicationException : Exception\n  inheritance:\n  - System.Exception\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.ApplicationException.#ctor\n  id: '#ctor'\n  parent: System.ApplicationException\n  langs:\n  - csharp\n  name: ApplicationException()\n  nameWithType: ApplicationException.ApplicationException()\n  fullName: System.ApplicationException.ApplicationException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"An application error has occurred.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ApplicationException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public ApplicationException ();\n    parameters: []\n  overload: System.ApplicationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ApplicationException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.ApplicationException\n  langs:\n  - csharp\n  name: ApplicationException(String)\n  nameWithType: ApplicationException.ApplicationException(String)\n  fullName: System.ApplicationException.ApplicationException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with a specified error message.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ApplicationException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|`Message`|The error message string.|\"\n  syntax:\n    content: public ApplicationException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A message that describes the error.\n  overload: System.ApplicationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.ApplicationException\n  langs:\n  - csharp\n  name: ApplicationException(SerializationInfo,StreamingContext)\n  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)\n  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).\n  syntax:\n    content: protected ApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.ApplicationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.ApplicationException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.ApplicationException\n  langs:\n  - csharp\n  name: ApplicationException(String,Exception)\n  nameWithType: ApplicationException.ApplicationException(String,Exception)\n  fullName: System.ApplicationException.ApplicationException(String,Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ApplicationException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ApplicationException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ApplicationException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.ApplicationException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Exception\n  isExternal: false\n  name: System.Exception\n- uid: System.ApplicationException.#ctor\n  parent: System.ApplicationException\n  isExternal: false\n  name: ApplicationException()\n  nameWithType: ApplicationException.ApplicationException()\n  fullName: System.ApplicationException.ApplicationException()\n- uid: System.ApplicationException.#ctor(System.String)\n  parent: System.ApplicationException\n  isExternal: false\n  name: ApplicationException(String)\n  nameWithType: ApplicationException.ApplicationException(String)\n  fullName: System.ApplicationException.ApplicationException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.ApplicationException\n  isExternal: false\n  name: ApplicationException(SerializationInfo,StreamingContext)\n  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)\n  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.ApplicationException.#ctor(System.String,System.Exception)\n  parent: System.ApplicationException\n  isExternal: false\n  name: ApplicationException(String,Exception)\n  nameWithType: ApplicationException.ApplicationException(String,Exception)\n  fullName: System.ApplicationException.ApplicationException(String,Exception)\n- uid: System.ApplicationException.#ctor*\n  parent: System.ApplicationException\n  isExternal: false\n  name: ApplicationException\n  nameWithType: ApplicationException.ApplicationException\n"}