{"nodes":[{"pos":[705,778],"content":"The exception that is thrown when an operation in isolated storage fails.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when an operation in isolated storage fails.","pos":[0,73]}]},{"pos":[791,1532],"content":"`IsolatedStorageException` uses the HRESULT ISS_E_ISOSTORE, which has the value 0x80131450.       The most common examples of isolated storage exceptions are as follows.      -   Missing evidence. Isolated storage requires evidence (information about the assembly and its origin) in order to determine the identity of the code and connect it to the correct associated file space. Without this information, isolated storage cannot be used.      -   Invalid operations. Some <xref:System.IO.FileStream> operations are not supported for isolated storage.       For a list of initial property values for an instance of `IsolatedStorageException`, see the <xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A> constructors.","needQuote":false,"needEscape":true,"nodes":[{"content":"<ph id=\"ph1\">`IsolatedStorageException`</ph> uses the HRESULT ISS_E_ISOSTORE, which has the value 0x80131450.","pos":[0,91],"source":"`IsolatedStorageException` uses the HRESULT ISS_E_ISOSTORE, which has the value 0x80131450."},{"content":"The most common examples of isolated storage exceptions are as follows.","pos":[98,169]},{"content":"-   Missing evidence.","pos":[175,196]},{"content":"Isolated storage requires evidence (information about the assembly and its origin) in order to determine the identity of the code and connect it to the correct associated file space.","pos":[197,379]},{"content":"Without this information, isolated storage cannot be used.","pos":[380,438]},{"content":"-   Invalid operations.","pos":[444,467]},{"content":"Some &lt;xref:System.IO.FileStream&gt; operations are not supported for isolated storage.","pos":[468,551],"source":" Some <xref:System.IO.FileStream> operations are not supported for isolated storage."},{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">`IsolatedStorageException`</ph>, see the &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A&gt; constructors.","pos":[558,733],"source":"       For a list of initial property values for an instance of `IsolatedStorageException`, see the <xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A> constructors."}]},{"pos":[2221,2357],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with default properties.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with default properties."},{"pos":[2370,2688],"content":"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[137,313],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]},{"pos":[3375,3518],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with a specified error message."},{"pos":[3531,3839],"content":"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[137,303],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[3993,4054],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[4904,5037],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with serialized data."},{"pos":[5049,5162],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","needQuote":true,"needEscape":true,"nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]}]},{"pos":[5440,5489],"content":"The object that holds the serialized object data.","needQuote":true,"needEscape":true,"nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]},{"pos":[5585,5644],"content":"The contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]},{"pos":[6316,6534],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[6547,7314],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor, or <ph id=\"ph1\">`null`</ph> if the &lt;xref:System.Exception.InnerException%2A&gt; property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."},{"content":"The following table shows the initial property values for an instance of &lt;xref:System.IO.IsolatedStorage.IsolatedStorageException&gt;.","pos":[434,565],"source":"       The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>."},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[571,760],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[7485,7546],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[7611,7902],"content":"The exception that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <ph id=\"ph1\">`inner`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[58,291],"source":" If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.IO.IsolatedStorage.IsolatedStorageException\n  id: IsolatedStorageException\n  children:\n  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor\n  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)\n  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: IsolatedStorageException\n  nameWithType: IsolatedStorageException\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException\n  type: Class\n  summary: The exception that is thrown when an operation in isolated storage fails.\n  remarks: \"`IsolatedStorageException` uses the HRESULT ISS_E_ISOSTORE, which has the value 0x80131450.  \\n  \\n The most common examples of isolated storage exceptions are as follows.  \\n  \\n-   Missing evidence. Isolated storage requires evidence (information about the assembly and its origin) in order to determine the identity of the code and connect it to the correct associated file space. Without this information, isolated storage cannot be used.  \\n  \\n-   Invalid operations. Some <xref:System.IO.FileStream> operations are not supported for isolated storage.  \\n  \\n For a list of initial property values for an instance of `IsolatedStorageException`, see the <xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A> constructors.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class IsolatedStorageException : Exception\n  inheritance:\n  - System.Exception\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor\n  id: '#ctor'\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  langs:\n  - csharp\n  name: IsolatedStorageException()\n  nameWithType: IsolatedStorageException.IsolatedStorageException()\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.IO.IsolatedStorage\n  summary: Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with default properties.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public IsolatedStorageException ();\n    parameters: []\n  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  langs:\n  - csharp\n  name: IsolatedStorageException(String)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(String)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.IO.IsolatedStorage\n  summary: Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public IsolatedStorageException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  langs:\n  - csharp\n  name: IsolatedStorageException(SerializationInfo,StreamingContext)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.IO.IsolatedStorage\n  summary: Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.\n  syntax:\n    content: protected IsolatedStorageException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  langs:\n  - csharp\n  name: IsolatedStorageException(String,Exception)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.IO.IsolatedStorage\n  summary: Initializes a new instance of the <xref href=\"System.IO.IsolatedStorage.IsolatedStorageException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.IO.IsolatedStorage.IsolatedStorageException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public IsolatedStorageException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Exception\n  isExternal: false\n  name: System.Exception\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  isExternal: false\n  name: IsolatedStorageException()\n  nameWithType: IsolatedStorageException.IsolatedStorageException()\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  isExternal: false\n  name: IsolatedStorageException(String)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(String)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  isExternal: false\n  name: IsolatedStorageException(SerializationInfo,StreamingContext)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  isExternal: false\n  name: IsolatedStorageException(String,Exception)\n  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)\n  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)\n- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*\n  parent: System.IO.IsolatedStorage.IsolatedStorageException\n  isExternal: false\n  name: IsolatedStorageException\n  nameWithType: IsolatedStorageException.IsolatedStorageException\n"}