{"nodes":[{"pos":[397,505],"content":"Provides data for the <bpt id=\"p1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> event.","needQuote":true,"needEscape":true,"source":"Provides data for the <xref href=\"System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated\"></xref> event."},{"pos":[518,1321],"content":"> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]       A workflow instance may be terminated in one of three ways: the host may call <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, a <xref:System.Workflow.ComponentModel.TerminateActivity> activity may be invoked from inside the workflow instance, or the workflow runtime engine may terminate the instance because of an unhandled exception. When the workflow instance is terminated, the workflow runtime engine raises the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event. The host may subscribe to this event by adding an event handler to <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"<ph id=\"ph1\">&gt; [!NOTE]</ph><ph id=\"ph2\"> &gt;  </ph><ph id=\"ph3\">[!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]</ph>       A workflow instance may be terminated in one of three ways: the host may call &lt;xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName&gt;, a &lt;xref:System.Workflow.ComponentModel.TerminateActivity&gt; activity may be invoked from inside the workflow instance, or the workflow runtime engine may terminate the instance because of an unhandled exception.","pos":[0,462],"source":"> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]       A workflow instance may be terminated in one of three ways: the host may call <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, a <xref:System.Workflow.ComponentModel.TerminateActivity> activity may be invoked from inside the workflow instance, or the workflow runtime engine may terminate the instance because of an unhandled exception."},{"content":"When the workflow instance is terminated, the workflow runtime engine raises the &lt;xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName&gt; event.","pos":[463,641],"source":" When the workflow instance is terminated, the workflow runtime engine raises the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event."},{"content":"The host may subscribe to this event by adding an event handler to &lt;xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName&gt;.","pos":[642,800],"source":" The host may subscribe to this event by adding an event handler to <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>."}]},{"pos":[3083,3153],"content":"Gets the exception that caused the workflow instance to be terminated.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the exception that caused the workflow instance to be terminated.","pos":[0,70]}]},{"pos":[3166,4581],"content":"When the workflow instance is terminated because of an unhandled exception, Exception contains the unhandled exception.       When the workflow instance is terminated by either a host call to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> or by a <xref:System.Workflow.ComponentModel.TerminateActivity> activity,    Exception contains a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException> that has its <xref:System.Exception.Message%2A> property set to a description of the reason for the termination. If the host terminates the workflow instance, it supplies this description in the `string` parameter to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>. If the workflow instance is terminated by a <xref:System.Workflow.ComponentModel.TerminateActivity>, the description is supplied by <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>.      > [!NOTE] >  Although in the case of a <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event that is not due to an unhandled exception, the workflow runtime engine encapsulates a description of the reason for the termination in the <xref:System.Exception.Message%2A> property of a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, it does not necessarily throw this exception.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"When the workflow instance is terminated because of an unhandled exception, Exception contains the unhandled exception.","pos":[0,119]},{"content":"When the workflow instance is terminated by either a host call to &lt;xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName&gt; or by a &lt;xref:System.Workflow.ComponentModel.TerminateActivity&gt; activity,    Exception contains a &lt;xref:System.Workflow.ComponentModel.WorkflowTerminatedException&gt; that has its &lt;xref:System.Exception.Message%2A&gt; property set to a description of the reason for the termination.","pos":[126,554],"source":"       When the workflow instance is terminated by either a host call to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> or by a <xref:System.Workflow.ComponentModel.TerminateActivity> activity,    Exception contains a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException> that has its <xref:System.Exception.Message%2A> property set to a description of the reason for the termination."},{"content":"If the host terminates the workflow instance, it supplies this description in the <ph id=\"ph1\">`string`</ph> parameter to &lt;xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName&gt;.","pos":[555,745],"source":" If the host terminates the workflow instance, it supplies this description in the `string` parameter to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>."},{"content":"If the workflow instance is terminated by a &lt;xref:System.Workflow.ComponentModel.TerminateActivity&gt;, the description is supplied by &lt;xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName&gt;.","pos":[746,968],"source":" If the workflow instance is terminated by a <xref:System.Workflow.ComponentModel.TerminateActivity>, the description is supplied by <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>."},{"content":"&gt; <ph id=\"ph1\">[!NOTE]</ph> &gt;  Although in the case of a &lt;xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName&gt; event that is not due to an unhandled exception, the workflow runtime engine encapsulates a description of the reason for the termination in the &lt;xref:System.Exception.Message%2A&gt; property of a &lt;xref:System.Workflow.ComponentModel.WorkflowTerminatedException&gt;, it does not necessarily throw this exception.","pos":[974,1410],"source":"      > [!NOTE] >  Although in the case of a <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event that is not due to an unhandled exception, the workflow runtime engine encapsulates a description of the reason for the termination in the <xref:System.Exception.Message%2A> property of a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, it does not necessarily throw this exception."}]},{"pos":[5659,5738],"content":"The <xref:System.Exception> that caused the workflow instance to be terminated.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Exception&gt; that caused the workflow instance to be terminated.","pos":[0,79],"source":"The <xref:System.Exception> that caused the workflow instance to be terminated."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs\n  id: WorkflowTerminatedEventArgs\n  children:\n  - System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception\n  langs:\n  - csharp\n  name: WorkflowTerminatedEventArgs\n  nameWithType: WorkflowTerminatedEventArgs\n  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs\n  type: Class\n  summary: Provides data for the <xref href=\"System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated\"></xref> event.\n  remarks: \"> [!NOTE]\\n>  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]  \\n  \\n A workflow instance may be terminated in one of three ways: the host may call <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, a <xref:System.Workflow.ComponentModel.TerminateActivity> activity may be invoked from inside the workflow instance, or the workflow runtime engine may terminate the instance because of an unhandled exception. When the workflow instance is terminated, the workflow runtime engine raises the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event. The host may subscribe to this event by adding an event handler to <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>.\"\n  example:\n  - \"The following code example demonstrates an event handler method that takes WorkflowTerminatedEventArgs as a parameter. The `OnWorkflowTerminated` method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception%2A> property get the message associated with the exception that caused the workflow to terminate.  \\n  \\n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \\n  \\n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]\"\n  syntax:\n    content: >-\n      [System.Obsolete(\"The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*\")]\n\n      public class WorkflowTerminatedEventArgs : System.Workflow.Runtime.WorkflowEventArgs\n  inheritance:\n  - System.EventArgs\n  - System.Workflow.Runtime.WorkflowEventArgs\n  implements: []\n  inheritedMembers:\n  - System.Workflow.Runtime.WorkflowEventArgs.WorkflowInstance\n  platform:\n  - net462\n- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception\n  id: Exception\n  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs\n  langs:\n  - csharp\n  name: Exception\n  nameWithType: WorkflowTerminatedEventArgs.Exception\n  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception\n  type: Property\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Gets the exception that caused the workflow instance to be terminated.\n  remarks: \"When the workflow instance is terminated because of an unhandled exception, Exception contains the unhandled exception.  \\n  \\n When the workflow instance is terminated by either a host call to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> or by a <xref:System.Workflow.ComponentModel.TerminateActivity> activity,    Exception contains a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException> that has its <xref:System.Exception.Message%2A> property set to a description of the reason for the termination. If the host terminates the workflow instance, it supplies this description in the `string` parameter to <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>. If the workflow instance is terminated by a <xref:System.Workflow.ComponentModel.TerminateActivity>, the description is supplied by <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>.  \\n  \\n> [!NOTE]\\n>  Although in the case of a <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> event that is not due to an unhandled exception, the workflow runtime engine encapsulates a description of the reason for the termination in the <xref:System.Exception.Message%2A> property of a <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, it does not necessarily throw this exception.\"\n  example:\n  - \"The following code example demonstrates how you can use the Exception property to obtain information about an exception that caused a workflow to terminate. The `OnWorkflowTerminated` method takes a <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs> as a parameter. This method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the Exception property get the message associated with the exception that caused the workflow to terminate.  \\n  \\n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \\n  \\n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]\"\n  syntax:\n    content: public Exception Exception { get; }\n    return:\n      type: System.Exception\n      description: The <xref:System.Exception> that caused the workflow instance to be terminated.\n  overload: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Workflow.Runtime.WorkflowEventArgs\n  isExternal: false\n  name: System.Workflow.Runtime.WorkflowEventArgs\n- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception\n  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs\n  isExternal: false\n  name: Exception\n  nameWithType: WorkflowTerminatedEventArgs.Exception\n  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*\n  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs\n  isExternal: false\n  name: Exception\n  nameWithType: WorkflowTerminatedEventArgs.Exception\n"}